export const GET_DETAIL_BEGIN = "GET_DETAIL_BEGIN";
export const GET_DETAIL_SUCCESS = "GET_DETAIL_SUCCESS";
export const GET_DETAIL_FAIL = "GET_DETAIL_FAIL";

export const POST_REVIEW_BEGIN = "POST_REVIEW_BEGIN";
export const POST_REVIEW_SUCCESS = "POST_REVIEW_SUCCESS";
export const POST_REVIEW_FAIL = "POST_REVIEW_FAIL";

export const LOAD_ALL_MOVIE = "LOAD_MOVIE"
export const ADD_MOVIE = "ADD_MOVIE"

export const DETAIL_USER = "DETAIL_USER"