export const GET_MOVIE = "GET_MOVIE"


export const GET_DETAIL_BEGIN = "GET_DETAIL_BEGIN";
export const GET_DETAIL_SUCCESS = "GET_DETAIL_SUCCESS";
export const GET_DETAIL_FAIL = "GET_DETAIL_FAIL";

export const POST_REVIEW_BEGIN = "POST_REVIEW_BEGIN";
export const POST_REVIEW_SUCCESS = "POST_REVIEW_SUCCESS";
export const POST_REVIEW_FAIL = "POST_REVIEW_FAIL";

export const GET_MOVIE_DETAIL_BEGIN = "GET_MOVIE_DETAIL_BEGIN";
export const GET_MOVIE_DETAIL_SUCCESS = "GET_MOVIE_DETAIL_SUCCESS";
export const GET_MOVIE_DETAIL_FAIL = "GET_MOVIE_DETAIL_FAIL";
export const ADD_MOVIE = "ADD_MOVIE"
export const DELETE_MOVIE = "DELETE_MOVIE"

export const DETAIL_USER = "DETAIL_USER"
export const DELETE_USER = "DELETE_USER"

export const LOAD_ALL_REVIEW = "LOAD_REVIEW"